tune allow-axfr-ips in pdns.conf, run pdns config check, copy server.pem at start

diff --git a/bin/start_pdns b/bin/start_pdns
--- a/bin/start_pdns
+++ b/bin/start_pdns
@@ -2,4 +2,12 @@
 # (c) Copyright 2019-2022, James Stevens ... see LICENSE for details
 # Alternative license arrangements possible, contact me for more information
 
+if ! pdns_server --config=check &> /run/pdns_check.log
+	then
+		logger -t pdns "ERROR: PowerDNS config failed check"
+		logger -t pdns < /run/pdns_check.log
+		sleep 5
+		exit 1
+	fi
+
 exec /usr/sbin/pdns_server 2>&1 | logger -t pdns
